### ISSUE TITLE
SyntaxError: leading zeros in decimal integer literals are not permitted; use an 0o prefix for octal integers

### ISSUE THREAD

**Issue by leihan11** [hashinami46/sakamichi-app-ts-cli#1]
both hinakoi and sakukoi didn't work, I'm sure I have catalog correctly in the directory
 `File "<string>", line 32
    if 03000 >= len(data["data"]) or 03500 >= len(data["data"]):
       ^
SyntaxError: leading zeros in decimal integer literals are not permitted; use an 0o prefix for octal integers`

**Comment by hashinami46** [comment]
Hello sir! Thanks for reporting. 
Did you extracted the catalog and give it the proper name?
And please make sure that your python3 is updated.

**Comment by 64600013** [comment]
> Hello sir! Thanks for reporting. Did you extracted the catalog and give it the proper name? And please make sure that your python3 is updated.

I think I'm also experiencing a similar problem, but I'm not sure I got the catalog extracted correctly. Would it be possible for you to elaborate a little more on that? Thanks.

**Comment by hashinami46** [comment]
Nothing wrong with the catalog that you provided I guess. I do a bit discussion with my friend, the error you mentioned above is caused by typedata error. Which means, the data you entered should be int, but the python script read it as string. Don't worry, I already added string manipulation logic to force str to int. Please use the latest update..

You can see the latest documentation to extract the catalog.
